"""
Carraretto Gabriel H.
image_info
Fetches the resolution values from a set of images, and save the info as
txt files
"""

import os
import glob
from PIL import Image


def get_resolution(path_name: str) -> str:
    """
    Given a path of a txt generated by generate_image_info, returns its
    content
    :param str path_name: path of the txt file
    :return str: resolution of an image specified by path_name
    """
    with open(path_name, 'r') as img_file:
        return img_file.read()


def generate_image_info(path: str):
    """
    Given a path, creates a folder for the output, if it doesn't exists,
    and saves on the output folder for each image a txt containing its
    resolution
    :param str path: path of the images
    """
    try:
        os.mkdir(path + '/out_img/')
    except FileExistsError:
        print(path + " already exists...")
    for img_path in glob.glob(path + '*.png'):
        img = Image.open(img_path)
        img_name = img_path.split('/')[-1].split('.')[0].split('_')[0]
        with open(path + '/out/' + img_name + '.txt', 'w') as file:
            file.write(str(img.size[0]) + 'x' + str(img.size[1]))
