"""
@author Carraretto Gabriel H.
@license MIT
Fetches the resolution values from a set of images, and save the info as
txt files
"""

import mmap
import glob
from PIL import Image
import sys


def get_resolution(path_name: str, file_name: str) -> list:
    """
    Given a path of a txt generated by generate_image_info, and the name
    of the file, returns a list containing the resolution of that file
    :param str path_name: path of the txt file
    :param str file_name: name of the given txt file
    :return str: resolution of an image specified by path_name
    """
    with open(path_name + 'resolution.txt') as file, \
            mmap.mmap(file.fileno(), 0, access=mmap.ACCESS_READ) as s:
        file.seek(0, s.find(file_name.encode()))
        line = file.readline().split(' ')
        return [line[1], line[2].rstrip('\n')]


def generate_image_info(path: str):
    """
    Given a path containing images, creates txt containing the name and
    resolution of each image in the given path
    :param str path: path of the images
    """
    file_types = ['*.png', '*.jpg', '*.gif']
    for file_type in file_types:
        for img_path in glob.glob(path + file_type):
            img = Image.open(img_path)
            img_name = img_path.split('/')[-1].split('.')[0]
            with open(path + 'resolution.txt', 'a') as file:
                file.write(img_name + ' ' + str(img.size[0]) +
                           ' ' + str(img.size[1]) + '\n')


if __name__ == '__main__':
    arg_path = sys.argv[1]
    generate_image_info(arg_path)
